spring:
  datasource:
    url: jdbc:mysql://150.158.5.94:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    #更新或创建数据表结构
    hibernate:
      ddl-auto: update
    #控制台显示SQL语句
    show-sql: true